INSERT INTO DEPTO VALUES (1, 'INFORMATICA');

INSERT INTO DEPTO VALUES (2, 'ENGENHARIA');

INSERT INTO DISCIPLINA VALUES (1, 1, 'DISCIPLINA 1', 4);
INSERT INTO DISCIPLINA VALUES (1, 2, 'DISCIPLINA 2', 4);
INSERT INTO DISCIPLINA VALUES (1, 3, 'DISCIPLINA 3', 4);
INSERT INTO DISCIPLINA VALUES (1, 4, 'DISCIPLINA 4', 4);
INSERT INTO DISCIPLINA VALUES (2, 1, 'DISCIPLINA 5', 4);
INSERT INTO DISCIPLINA VALUES (2, 2, 'DISCIPLINA 6', 4);

INSERT INTO PREREQ VALUES (1,4, 1,2);
INSERT INTO PREREQ VALUES (2,2, 2,1);

INSERT INTO TURMA VALUES ('20082', 1, 1, 'A', 30);
INSERT INTO TURMA VALUES ('20091', 2, 1, 'A', 50);

INSERT INTO PREDIO VALUES (1, 'PREDIO 1');
INSERT INTO PREDIO VALUES (2, 'PREDIO 2');

INSERT INTO SALA VALUES (1, 1, 30);
INSERT INTO SALA VALUES (2, 2, 30);

INSERT INTO HORARIO VALUES ('20082', 1, 1, 'A', '1', '08:30', 1, 1, 1);
INSERT INTO HORARIO VALUES ('20091', 2, 1, 'A', '2', '19:00', 1, 2, 2);

INSERT INTO TITULACAO VALUES (1, 'GRADUADO');
INSERT INTO TITULACAO VALUES (2, 'ESPECIALIS');
INSERT INTO TITULACAO VALUES (3, 'MESTRE');
INSERT INTO TITULACAO VALUES (4, 'DOUTORADO');

INSERT INTO PROFESSOR VALUES (1, 'PROFESSOR 1', 1, 1);
INSERT INTO PROFESSOR VALUES (2, 'PROFESSOR 2', 1, 2);
INSERT INTO PROFESSOR VALUES (3, 'PROFESSOR 3', 1, 2);
INSERT INTO PROFESSOR VALUES (4, 'PROFESSOR 4', 2, 1);
INSERT INTO PROFESSOR VALUES (5, 'PROFESSOR 5', 2, 1);

INSERT INTO PROFTURMA VALUES ('20082', 1, 1, 'A', 1);
INSERT INTO PROFTURMA VALUES ('20091', 2, 1, 'A', 2);
INSERT INTO PROFTURMA VALUES ('20082', 1, 1, 'A', 4);






